name: CI/CD Workflow with Pylint and Pytest

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pylint
        run: |
          $env:PYTHONPATH = (Get-Location).Path
          pylint **/*.py

  test:
    runs-on: windows-latest
    needs: lint
    if: ${{ github.event.inputs.skip_tests != 'true' }}  # Only run tests if skip_tests is not true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies for tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print PYTHONPATH
        run: |
          echo $env:PYTHONPATH          

      - name: Add src to PYTHONPATH
        run: |
          $env:PYTHONPATH = (Get-Location).Path + "\src"
          echo "PYTHONPATH=$env:PYTHONPATH"  # Output PYTHONPATH for debugging

      - name: Run tests with PYTHONPATH
        run: |
          $env:PYTHONPATH = "$(Get-Location)\src"
          pytest src/tests --disable-warnings
