name: CI/CD Workflow for ML Project

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  lint:
    name: Lint Code
    runs-on: windows-latest  # Specify OS for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint  # Install pylint for linting

      - name: Run pylint
        run: |
          $env:PYTHONPATH = (Get-Location).Path
          pylint **/*.py  # Lint all Python files in the repository

  test:
    name: Test Code
    runs-on: windows-latest
    needs: lint  # Run tests after linting completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run Pytest
        run: pytest tests  # Run tests in the `tests` directory

  deploy:
    name: Deploy Model
    runs-on: ubuntu-latest  # Use Linux for Docker compatibility
    needs: test  # Run deployment after tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ DOCKER_PASSWORD }}" | docker login -u "${{ DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/joblib-diabetes:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/joblib-diabetes:latest
